# Constants
SERVICE_MEAN_TRAY = 30  # seconds
SERVICE_MEAN_XRAY = 30
SERVICE_MEAN_BODYSCREEN = 30

NUM_CONTROL_AREAS = 5
NUM_TRAY_AREAS = 4 * NUM_CONTROL_AREAS
NUM_XRAYS = 4 * NUM_CONTROL_AREAS
NUM_BODYSCREENS = 2 * NUM_CONTROL_AREAS

TRAY_CAPACITY = 4 * NUM_TRAY_AREAS
XRAY_CAPACITY = 1 * NUM_XRAYS
BODYSCREEN_CAPACITY = 1 * NUM_BODYSCREENS

BODYSCREEN_WAITING_CAPACITY = 10 * NUM_BODYSCREENS
INPUT_PATH = 'inputs/passenger_arrival_process.csv'
OUTPUT_PATH = '../outputs/'
LOG_PATH = '../logs/'